### ISSUE TITLE
Use of zero-length Variable Length Arrays

### ISSUE THREAD

**Issue by aido** [BlockchainCommons/bc-sskr#18]
Hi,

I am using bc-sskr in an application I am writing to generate SSKR shares on Ledger hardware wallet devices: [SSKR Check](https://github.com/aido/app-sskr-check)
Clang Static Analyzer is giving a few warnings about the use of variable length arrays which maybe you would like to be aware of.

See here:
https://github.com/aido/app-sskr-check/actions/runs/4710379091/jobs/8353972683
```C
src/bc-sskr/encoding.c:162:26: warning: variable length array used [-Wvla]
    uint8_t group_shares[master_secret_len * groups_len];
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/bc-sskr/encoding.c:178:31: warning: variable length array used [-Wvla]
        uint8_t member_shares[master_secret_len * groups[i].count];
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.
.
.
src/bc-sskr/encoding.c:249:23: warning: variable length array used [-Wvla]
    sskr_shard shards[total_shards];
                      ^~~~~~~~~~~~
src/bc-sskr/encoding.c:382:26: warning: variable length array used [-Wvla]
    uint8_t group_shares[secret_len * (group_threshold + 1)];
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/bc-sskr/encoding.c:467:23: warning: variable length array used [-Wvla]
    sskr_shard shards[shards_count];
                      ^~~~~~~~~~~~
```
https://github.com/BlockchainCommons/bc-sskr/blob/84e1e76fda3155fd8805c1618cb56fb42f9681c7/src/encoding.c#L176
https://github.com/BlockchainCommons/bc-sskr/blob/84e1e76fda3155fd8805c1618cb56fb42f9681c7/src/encoding.c#L186
https://github.com/BlockchainCommons/bc-sskr/blob/84e1e76fda3155fd8805c1618cb56fb42f9681c7/src/encoding.c#L253
https://github.com/BlockchainCommons/bc-sskr/blob/84e1e76fda3155fd8805c1618cb56fb42f9681c7/src/encoding.c#L382
https://github.com/BlockchainCommons/bc-sskr/blob/84e1e76fda3155fd8805c1618cb56fb42f9681c7/src/encoding.c#L470

**Comment by wolfmcnally** [comment]
The static analyzer is turning on all warnings. The warning you're receiving, `-Wvla`, is not a concern as the SSKR implementation uses variable-length arrays by design. The warning is intended to convey that some (especially before C99) C compilers may not support variable length arrays. As you're obviously able to compile despite the warning, you have a compliant compiler. Since this is the case, I recommend you find a way to ignore the warning. I haven't tried it, but it may be as simple as adding `-Wno-vla` to your CFLAGS environment variable.

**Comment by aido** [comment]
Hi @wolfmcnally,

Ledger enforce certain [security guidelines](https://developers.ledger.com/docs/embedded-app/secure-app/). I am already bending those rules by adding `-disable-checker core.VLASize` to the `scan-build` command. This makes `scan-build` just give a warning on VLA rather than failing altogether.

But, thanks for the above tip, I'll see if I can work around it.

**Comment by aido** [comment]
Hi @wolfmcnally,

Closer inspection of one of the warnings is that a zero-length VLA is being declared.

The static analyzer seems to think  `sskr_shard shards[total_shards]` is being declared as a zero-length array and zero-length arrays are explicitly prohibited by C language, even if they are created as VLA, I think it is explained somewhere here: https://en.cppreference.com/w/c/language/array

```
src/bc-sskr/encoding.c:253:5: warning: Declared variable-length array (VLA) has zero size [core.VLASize]
    sskr_shard shards[total_shards];
    ^~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~
1 warning generated.
```

**Comment by aido** [comment]
Hi @wolfmcnally,

OK, I see where the issue is.

```
src/bc-sskr/encoding.c:253:5: warning: Declared variable-length array (VLA) has zero size [core.VLASize]
    sskr_shard shards[total_shards];
    ^~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~
1 warning generated.
```

The static analyzer gives the above warning about `sskr_shard shards[total_shards]` on line 253 of `bc-sskr/encoding.c` because we do not ensure that `total_shards` is not 0.

The fix would be to change line 239 to exit if `total_shards` is 0.
i.e. change:
```C
    if(total_shards < 0) {
        return total_shards;
    }
```
https://github.com/BlockchainCommons/bc-sskr/blob/84e1e76fda3155fd8805c1618cb56fb42f9681c7/src/encoding.c#LL239C1-L241C1

to:
```C
    if(total_shards <= 0) {
        return total_shards;
    }
```
This ensures `total_shards` is never 0 which in turn ensures we will never declare `sskr_shard shards[total_shards]` as a zero-length array.

So, is there a case where `total_shards` will or should be 0?

**Comment by wolfmcnally** [comment]
No legal case. If you're calling into this library you're always trying to create at least one shard.

**Comment by aido** [comment]
OK, I'll make the above suggested change, test to make sure it doesn't break anything in app-sskr-check and if all is hunky dory will create a PR for bc-sskr for your approval.

**Comment by ChristopherA** [comment]
But isn’t it reasonable as defensive programming?

**Comment by aido** [comment]
Maybe my suggested change above is just a quick fix to get rid of a static analyzer warning. But `total_shards` which should never be 0 is causing static analyzer warnings because bc-sskr does not test to make sure it isn't 0.

`total_shards` is the value returned from `sskr_count_shards()`. This returned value is a sum of `groups[i].count`.This sum depends on what values are passed to `sskr_generate()` by whatever program calls it, in this case app-sskr-check.
app-sskr-check makes sure that `groups[i].count` and `groups_len` is never 0 but bc-sskr never checks this.

If `groups_len` and `groups[i].count` should never be 0 should bc-sskr return an error if another program passes incorrect 0 values to `sskr_generate()`? 

Maybe a few extra lines in the `sskr_count_shards()` function?
```C
if(groups_len < 1) {
    return SSKR_ERROR_INVALID_GROUP_LENGTH;
}
.
.
.
if(groups[i].count < 1) {
    return SSKR_ERROR_INVALID_GROUP_COUNT;
}
```
That's the long way of asking if bc-sskr should be validating more of the values passed to it? :-)

It already does some validation e.g.:
```C
if (group_threshold > groups_len) {
    return SSKR_ERROR_INVALID_GROUP_THRESHOLD;
}
````
